python -m pip install flask
python -m pip install flask-login
python -m pip install flask-openid
python -m pip install flask-mail
python -m pip install flask-sqlalchemy
python -m pip install sqlalchemy-migrate
python -m pip install flask-whooshalchemy
python -m pip install flask-wtf
python -m pip install flask-babel
python -m pip install guess_language
python -m pip install flipflop
python -m pip install coverage
python -m pip install flask-bcrypt