# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('body', models.TextField(verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('test_time', models.DateTimeField(verbose_name='\u6d4b\u8bd5\u65f6\u95f4a')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u56fe\u7247\u6807\u9898')),
                ('addtime', models.IntegerField(default=10, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(max_length=255, verbose_name='\u7f29\u7565\u56fe\u7f51\u5740')),
                ('filepath', models.CharField(max_length=255, verbose_name='\u7f29\u7565\u56fe\u7f51\u5740')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u59d3\u540d')),
                ('url', models.CharField(max_length=255, verbose_name='\u7f51\u5740')),
                ('blognums', models.IntegerField(default=11, verbose_name='\u535a\u5ba2\u6570\u76ee')),
                ('show', models.BooleanField(verbose_name='\u662f\u5426\u663e\u793a')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User'),
        ),
    ]
