# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='test_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6d4b\u8bd5\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='filepath',
            field=models.CharField(max_length=255, null=True, verbose_name='\u7f29\u7565\u56fe\u7f51\u5740'),
        ),
    ]
