# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20170325_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '\u535a\u5ba2\u7ba1\u7406', 'verbose_name_plural': '\u535a\u5ba2\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '\u76f8\u518c\u7ba1\u7406', 'verbose_name_plural': '\u76f8\u518c\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='photodata',
            options={'verbose_name': '\u7167\u7247\u7ba1\u7406', 'verbose_name_plural': '\u7167\u7247\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237\u7ba1\u7406', 'verbose_name_plural': '\u7528\u6237\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='blog',
            name='files',
            field=models.FileField(default='', upload_to=b'', verbose_name='/media/uploads'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='addtime',
            field=models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a'),
        ),
    ]
