# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20170329_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='files',
            field=models.FileField(default='', upload_to=b'', verbose_name='/media/uploads/'),
        ),
    ]
