# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20170329_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagefiles',
            field=models.ImageField(default='', upload_to='uploads', verbose_name='\u56fe\u7247\u4e0a\u4f20'),
        ),
    ]
