# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_blog_imagefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('local_default_image', models.CharField(max_length=255, verbose_name='\u9ed8\u8ba4\u56fe\u7247\u672c\u5730')),
                ('remote_default_image', models.CharField(max_length=255, verbose_name='\u9ed8\u8ba4\u56fe\u7247\u8fdc\u7a0b')),
                ('local_images_paths', models.TextField(verbose_name='\u672c\u5730\u56fe\u7247\u8def\u5f84\u6c47\u603b')),
                ('remote_images_paths', models.TextField(verbose_name='\u8fdc\u7a0b\u56fe\u7247\u8def\u5f84\u6c47\u603b')),
                ('addtime', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
            options={
                'verbose_name': 'lofter\u76f8\u518c',
                'verbose_name_plural': 'lofter\u76f8\u518c',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='files',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='\u6587\u4ef6\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagefiles',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='\u56fe\u7247\u4e0a\u4f20'),
        ),
    ]
