# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20170912_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='\u89c6\u9891\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
