# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20170912_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(default='', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='\u89c6\u9891\u56fe\u7247'),
        ),
    ]
