# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20170913_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('guid', models.CharField(default='', max_length=255, verbose_name='guid')),
                ('filepath', models.CharField(default='', max_length=255, null=True, verbose_name='\u4e66\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u7535\u5b50\u4e66',
                'verbose_name_plural': '\u7535\u5b50\u4e66',
            },
        ),
    ]
